# spring boot configuration

#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp

welcome:
   message: Welcome to PosLedger Assets

spring:
   jpa:
      jpagenerate-ddl: true
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
   
      # update while chainging database
      hibernate:
         ddl-auto: update
      
      properties:
         hibernate:
            show_sql=true
            format_sql=true
            use_sql_comments=true
   
   # datasource configuration
   datasource:
      type: org.apache.tomcat.jdbc.pool.DataSource
      driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      url: jdbc:log4jdbc:mysql://localhost:3306/hyperledger?autoReconnection=true&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
      username: root
      password: test1234
      tomcat:
         max-wait: 10000
         max-active: 50
         test-on-borrow: true

   http: 
      encoding:
         force: true
         force-request: true
         force-response: true

   redis:
      host: 127.0.0.1
      port: 6379

# server configuration
server:
   compression:
      enabled: false

   servlet:
      context-path: /assets

   port: 8080

   server:
      tomcat:
         uri-encoding: UTF-8

# log level
logging:
   level:
      org:
         springframework: debug
         hibernate: error
